param(
  [switch]$SkipFfmpegDownload,
  [switch]$SkipTwitchDownloaderDownload,
  [switch]$SkipTests,
  [switch]$InstallerOnly,
  [string]$UpdateUrl = $env:HIGHLIGHT_STUDIO_UPDATE_URL,
  [string]$BetaUpdateUrl = $env:HIGHLIGHT_STUDIO_BETA_UPDATE_URL,
  [switch]$RequireSigned,
  [switch]$MassRelease,
  [string]$MassReleaseEvidencePath = $env:HIGHLIGHT_STUDIO_RELEASE_EVIDENCE_PATH,
  [string]$BenchmarkReportPath = $env:HIGHLIGHT_STUDIO_BENCHMARK_REPORT_PATH
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Set-Location $Root
$BuildVenv = Join-Path $Root ".desktop-build-venv"
$TestVenv = Join-Path $Root ".desktop-test-venv"
$Version = (Get-Content (Join-Path $Root "desktop\electron\package.json") -Raw | ConvertFrom-Json).version
$ReleaseChannelPath = Join-Path $Root "desktop\electron\release-channel.json"

function Write-JsonUtf8([string]$Path, $Value) {
  $Json = $Value | ConvertTo-Json -Depth 8
  [System.IO.File]::WriteAllText($Path, $Json + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

function Get-ConfigValue($EnvironmentValue, $Existing, [string]$Name, $Fallback = "") {
  if (![string]::IsNullOrWhiteSpace([string]$EnvironmentValue)) { return $EnvironmentValue }
  if ($Existing -and $Existing.PSObject.Properties.Name -contains $Name) { return $Existing.$Name }
  return $Fallback
}

$ExistingRelease = if (Test-Path $ReleaseChannelPath) { Get-Content $ReleaseChannelPath -Raw | ConvertFrom-Json } else { $null }
$ReleaseChannel = @{
  channel = Get-ConfigValue $null $ExistingRelease "channel" "stable"
  stableUpdateUrl = Get-ConfigValue $UpdateUrl $ExistingRelease "stableUpdateUrl" ""
  betaUpdateUrl = Get-ConfigValue $BetaUpdateUrl $ExistingRelease "betaUpdateUrl" ""
  allowChannelSwitch = [bool](Get-ConfigValue $null $ExistingRelease "allowChannelSwitch" $true)
  notes = Get-ConfigValue $null $ExistingRelease "notes" "Generated by build_hybrid_release.ps1"
}
Write-JsonUtf8 $ReleaseChannelPath $ReleaseChannel
$PaidBetaChannelPath = Join-Path $Root "desktop\electron\paid-beta-channel.json"
$ExistingPaidBeta = if (Test-Path $PaidBetaChannelPath) { Get-Content $PaidBetaChannelPath -Raw | ConvertFrom-Json } else { $null }
$PaidBetaChannel = @{
  licensePublicKeyB64 = Get-ConfigValue $env:HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64 $ExistingPaidBeta "licensePublicKeyB64" ""
  licenseServerUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_LICENSE_SERVER_URL $ExistingPaidBeta "licenseServerUrl" ""
  checkoutUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_CHECKOUT_URL $ExistingPaidBeta "checkoutUrl" ""
  accountUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_ACCOUNT_URL $ExistingPaidBeta "accountUrl" ""
  supportUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_SUPPORT_URL $ExistingPaidBeta "supportUrl" ""
  privacyUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_PRIVACY_URL $ExistingPaidBeta "privacyUrl" ""
  termsUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_TERMS_URL $ExistingPaidBeta "termsUrl" ""
  telemetryUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_TELEMETRY_URL $ExistingPaidBeta "telemetryUrl" ""
  feedbackUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_FEEDBACK_URL $ExistingPaidBeta "feedbackUrl" ""
  crashReportUrl = Get-ConfigValue $env:HIGHLIGHT_STUDIO_CRASH_REPORT_URL $ExistingPaidBeta "crashReportUrl" ""
  trialDays = if ($env:HIGHLIGHT_STUDIO_TRIAL_DAYS) { [int]$env:HIGHLIGHT_STUDIO_TRIAL_DAYS } else { [int](Get-ConfigValue $null $ExistingPaidBeta "trialDays" 14) }
}
Write-JsonUtf8 $PaidBetaChannelPath $PaidBetaChannel
if ($RequireSigned -and !$UpdateUrl) { throw "A signed release requires -UpdateUrl or HIGHLIGHT_STUDIO_UPDATE_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH) { throw "A signed release requires HIGHLIGHT_STUDIO_SIGN_PFX_PATH." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_CHECKOUT_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_CHECKOUT_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_PRIVACY_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_PRIVACY_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_TERMS_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_TERMS_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_LICENSE_SERVER_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_LICENSE_SERVER_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_SUPPORT_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_SUPPORT_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_CRASH_REPORT_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_CRASH_REPORT_URL." }
if ($env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH -and !$env:CSC_LINK) { $env:CSC_LINK = $env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH }
if ($env:HIGHLIGHT_STUDIO_SIGN_PFX_PASSWORD -and !$env:CSC_KEY_PASSWORD) { $env:CSC_KEY_PASSWORD = $env:HIGHLIGHT_STUDIO_SIGN_PFX_PASSWORD }

function Run-Step([string]$Name, [scriptblock]$Action) {
  Write-Host "`n=== $Name ===" -ForegroundColor Cyan
  $global:LASTEXITCODE = 0
  & $Action
  if (!$?) { throw "$Name failed." }
  if ($LASTEXITCODE -ne 0) { throw "$Name failed with code $LASTEXITCODE" }
}

if (!$SkipFfmpegDownload) {
  if ([bool]$env:HIGHLIGHT_STUDIO_FFMPEG_URL -xor [bool]$env:HIGHLIGHT_STUDIO_FFMPEG_SHA256) {
    throw "Custom FFmpeg source requires both HIGHLIGHT_STUDIO_FFMPEG_URL and HIGHLIGHT_STUDIO_FFMPEG_SHA256."
  }
  $FfmpegArgs = @{ Force = $true }
  if ($env:HIGHLIGHT_STUDIO_FFMPEG_URL) {
    $FfmpegArgs.Url = $env:HIGHLIGHT_STUDIO_FFMPEG_URL
    $FfmpegArgs.Sha256 = $env:HIGHLIGHT_STUDIO_FFMPEG_SHA256
  }
  Run-Step "Prepare checksum-pinned bundled FFmpeg" { & (Join-Path $PSScriptRoot "fetch_ffmpeg.ps1") @FfmpegArgs }
}
if (!$SkipTwitchDownloaderDownload) {
  Run-Step "Prepare checksum-pinned TwitchDownloaderCLI" { & (Join-Path $PSScriptRoot "fetch_twitchdownloader.ps1") -Force }
}

if (!$InstallerOnly) {
  if (!(Test-Path $BuildVenv)) {
    Run-Step "Create production build virtual environment" { python -m venv $BuildVenv }
  }
  $Python = Join-Path $BuildVenv "Scripts\python.exe"
  Run-Step "Upgrade production build pip" { & $Python -m pip install --upgrade pip }
  Run-Step "Install production build dependencies" { & $Python -m pip install -r backend\requirements-build.txt }

  Run-Step "Install frontend dependencies" { npm --prefix frontend ci }
  Run-Step "Build frontend" { npm --prefix frontend run build }
  if (!$SkipTests) {
    if (!(Test-Path $TestVenv)) {
      Run-Step "Create test virtual environment" { python -m venv $TestVenv }
    }
    $TestPython = Join-Path $TestVenv "Scripts\python.exe"
    Run-Step "Upgrade test environment pip" { & $TestPython -m pip install --upgrade pip }
    Run-Step "Install Python test dependencies" { & $TestPython -m pip install -r backend\requirements-dev.txt }
    Run-Step "Backend tests" {
      $PytestLog = Join-Path $env:RUNNER_TEMP "highlight-studio-pytest.log"
      & $TestPython -m pytest -q 2>&1 | Tee-Object -FilePath $PytestLog
      $PytestExitCode = $LASTEXITCODE
      if ($PytestExitCode -ne 0) {
        $PytestTail = (Get-Content $PytestLog -Tail 100) -join "`n"
        $PytestAnnotation = $PytestTail.Replace("%", "%25").Replace("`r", "%0D").Replace("`n", "%0A")
        Write-Output "::error title=Backend test failure details::$PytestAnnotation"
        throw "Backend tests failed with code $PytestExitCode"
      }
    }
    Run-Step "Python lint" { & $TestPython -m ruff check backend tests tools }
    Run-Step "Python compileall" { & $TestPython -m compileall -q backend tools tests }
    Run-Step "Architecture audit" { & $TestPython tools\quality\architecture_audit.py }
    Run-Step "Frontend tests" {
      $FrontendTestLog = Join-Path $env:RUNNER_TEMP "highlight-studio-frontend-tests.log"
      npm --prefix frontend test 2>&1 | Tee-Object -FilePath $FrontendTestLog
      $FrontendTestExitCode = $LASTEXITCODE
      if ($FrontendTestExitCode -ne 0) {
        $FrontendTestTail = ((Get-Content $FrontendTestLog -Tail 60) | ForEach-Object { $_.Trim() }) -join " | "
        if ($FrontendTestTail.Length -gt 7000) { $FrontendTestTail = $FrontendTestTail.Substring($FrontendTestTail.Length - 7000) }
        $FrontendTestAnnotation = $FrontendTestTail.Replace("%", "%25")
        Write-Output "::error title=Frontend test failure details::$FrontendTestAnnotation"
        throw "Frontend tests failed with code $FrontendTestExitCode"
      }
    }
    Run-Step "Frontend lint" { npm --prefix frontend run lint }
    Run-Step "Frontend dependency audit" { npm --prefix frontend audit --audit-level=high }
  }

  $EngineDist = Join-Path $Root "build\desktop\engine"
  $EngineWork = Join-Path $Root "build\desktop\pyinstaller-work"
  Remove-Item $EngineDist -Recurse -Force -ErrorAction SilentlyContinue
  Remove-Item $EngineWork -Recurse -Force -ErrorAction SilentlyContinue
  Run-Step "Build standalone engine" {
    & $Python -m PyInstaller --noconfirm --clean --distpath $EngineDist --workpath $EngineWork tools\desktop\HighlightStudioEngine.spec
  }
  $EngineExe = Join-Path $EngineDist "HighlightStudioEngine\HighlightStudioEngine.exe"
  Run-Step "Verify packaged engine version and startup" {
    $EngineVerifyLog = Join-Path $env:RUNNER_TEMP "highlight-studio-engine-verify.log"
    $SavedErrorActionPreference = $ErrorActionPreference
    try {
      $ErrorActionPreference = "Continue"
      & $Python tools\desktop\verify_engine_runtime.py $EngineExe "v$Version" --app-root $Root 2>&1 | Tee-Object -FilePath $EngineVerifyLog
      $EngineVerifyExitCode = $LASTEXITCODE
    } finally {
      $ErrorActionPreference = $SavedErrorActionPreference
    }
    if ($EngineVerifyExitCode -ne 0) {
      $EngineVerifyTail = ((Get-Content $EngineVerifyLog -Tail 60) | ForEach-Object { $_.ToString().Trim() }) -join " | "
      $EngineVerifyTail = $EngineVerifyTail.Replace("`r", " ").Replace("`n", " ")
      if ($EngineVerifyTail.Length -gt 7000) { $EngineVerifyTail = $EngineVerifyTail.Substring($EngineVerifyTail.Length - 7000) }
      $EngineVerifyAnnotation = $EngineVerifyTail.Replace("%", "%25")
      Write-Output "::error title=Packaged engine verification details::$EngineVerifyAnnotation"
      throw "Packaged engine verification failed with code $EngineVerifyExitCode"
    }
  }
  Run-Step "Sign standalone engine when certificate is configured" { & (Join-Path $PSScriptRoot "sign_engine.ps1") -EnginePath $EngineExe }
}

$ValidatorPython = if (Test-Path (Join-Path $BuildVenv "Scripts\python.exe")) { Join-Path $BuildVenv "Scripts\python.exe" } else { "python" }
$PrereqArgs = @("tools\desktop\check_hybrid_prereqs.py", "--require-engine", "--require-windows-bins")
if ($UpdateUrl) { $PrereqArgs += "--require-update-url" }
if ($RequireSigned) { $PrereqArgs += "--require-paid-beta-config" }
Run-Step "Validate hybrid resources" { & $ValidatorPython @PrereqArgs }
if ($MassRelease) {
  if (!$MassReleaseEvidencePath -or !(Test-Path $MassReleaseEvidencePath)) { throw "Mass release requires -MassReleaseEvidencePath." }
  if (!$BenchmarkReportPath -or !(Test-Path $BenchmarkReportPath)) { throw "Mass release requires -BenchmarkReportPath." }
  $GateData = Join-Path $Root "build\mass-release-gate"
  New-Item -ItemType Directory -Path $GateData -Force | Out-Null
  Copy-Item $MassReleaseEvidencePath (Join-Path $GateData "mass_release_evidence.json") -Force
  Copy-Item $BenchmarkReportPath (Join-Path $GateData "quality_benchmark_report.json") -Force
  $env:HIGHLIGHT_STUDIO_DATA_DIR = $GateData
  $env:HIGHLIGHT_STUDIO_UPDATE_URL = [string]$UpdateUrl
  Run-Step "Mass release gate" { & $ValidatorPython tools\release\check_mass_release.py --strict }
}
Run-Step "Install Electron dependencies" { npm --prefix desktop\electron ci }
if (!$SkipTests) {
  Run-Step "Electron main syntax" { node --check desktop\electron\main.js }
  Run-Step "Electron preload syntax" { node --check desktop\electron\preload.js }
  Run-Step "Electron security tests" { npm --prefix desktop\electron test }
  Run-Step "Electron production dependency audit" { npm --prefix desktop\electron audit --omit=dev --audit-level=moderate }
  Run-Step "Electron dependency audit" { npm --prefix desktop\electron audit --audit-level=high }
}
Run-Step "Build NSIS installer and portable EXE" { npm --prefix desktop\electron run dist:win }
$ArtifactsDir = Join-Path $Root "build\desktop\installer"
Run-Step "Create auto-update manifest" { & $ValidatorPython tools\desktop\write_update_manifest.py $ArtifactsDir $Version }
Run-Step "Verify Windows artifacts" { & (Join-Path $PSScriptRoot "verify_windows_artifacts.ps1") -ArtifactsDir $ArtifactsDir -RequireSigned:$RequireSigned }

Write-Host "`nHybrid desktop artifacts:" -ForegroundColor Green
Get-ChildItem build\desktop\installer | Format-Table Name, Length, LastWriteTime
Write-Host "Runtime data will be stored in LOCALAPPDATA\HighlightStudio; projects in Videos\Highlight Studio."
