param(
  [switch]$SkipFfmpegDownload,
  [switch]$SkipTests,
  [switch]$InstallerOnly,
  [switch]$AllowUnverifiedFfmpegDownload,
  [string]$UpdateUrl = $env:HIGHLIGHT_STUDIO_UPDATE_URL,
  [string]$BetaUpdateUrl = $env:HIGHLIGHT_STUDIO_BETA_UPDATE_URL,
  [switch]$RequireSigned,
  [switch]$MassRelease,
  [string]$MassReleaseEvidencePath = $env:HIGHLIGHT_STUDIO_RELEASE_EVIDENCE_PATH,
  [string]$BenchmarkReportPath = $env:HIGHLIGHT_STUDIO_BENCHMARK_REPORT_PATH
)

$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
Set-Location $Root
$BuildVenv = Join-Path $Root ".desktop-build-venv"
$TestVenv = Join-Path $Root ".desktop-test-venv"
$Version = (Get-Content (Join-Path $Root "desktop\electron\package.json") -Raw | ConvertFrom-Json).version
$ReleaseChannelPath = Join-Path $Root "desktop\electron\release-channel.json"
$ReleaseChannel = @{ channel = "stable"; stableUpdateUrl = [string]$UpdateUrl; betaUpdateUrl = [string]$BetaUpdateUrl; allowChannelSwitch = $true; notes = "Generated by build_hybrid_release.ps1" }
$ReleaseChannel | ConvertTo-Json | Set-Content -Path $ReleaseChannelPath -Encoding UTF8
$PaidBetaChannelPath = Join-Path $Root "desktop\electron\paid-beta-channel.json"
$PaidBetaChannel = @{
  licensePublicKeyB64 = [string]$env:HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64
  licenseServerUrl = [string]$env:HIGHLIGHT_STUDIO_LICENSE_SERVER_URL
  checkoutUrl = [string]$env:HIGHLIGHT_STUDIO_CHECKOUT_URL
  accountUrl = [string]$env:HIGHLIGHT_STUDIO_ACCOUNT_URL
  supportUrl = [string]$env:HIGHLIGHT_STUDIO_SUPPORT_URL
  privacyUrl = [string]$env:HIGHLIGHT_STUDIO_PRIVACY_URL
  termsUrl = [string]$env:HIGHLIGHT_STUDIO_TERMS_URL
  telemetryUrl = [string]$env:HIGHLIGHT_STUDIO_TELEMETRY_URL
  feedbackUrl = [string]$env:HIGHLIGHT_STUDIO_FEEDBACK_URL
  crashReportUrl = [string]$env:HIGHLIGHT_STUDIO_CRASH_REPORT_URL
  trialDays = if ($env:HIGHLIGHT_STUDIO_TRIAL_DAYS) { [int]$env:HIGHLIGHT_STUDIO_TRIAL_DAYS } else { 14 }
}
$PaidBetaChannel | ConvertTo-Json | Set-Content -Path $PaidBetaChannelPath -Encoding UTF8
if ($RequireSigned -and !$UpdateUrl) { throw "A signed release requires -UpdateUrl or HIGHLIGHT_STUDIO_UPDATE_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH) { throw "A signed release requires HIGHLIGHT_STUDIO_SIGN_PFX_PATH." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_LICENSE_PUBLIC_KEY_B64." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_CHECKOUT_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_CHECKOUT_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_PRIVACY_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_PRIVACY_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_TERMS_URL) { throw "A signed Paid Beta release requires HIGHLIGHT_STUDIO_TERMS_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_LICENSE_SERVER_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_LICENSE_SERVER_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_SUPPORT_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_SUPPORT_URL." }
if ($RequireSigned -and !$env:HIGHLIGHT_STUDIO_CRASH_REPORT_URL) { throw "A signed release requires HIGHLIGHT_STUDIO_CRASH_REPORT_URL." }
if ($env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH -and !$env:CSC_LINK) { $env:CSC_LINK = $env:HIGHLIGHT_STUDIO_SIGN_PFX_PATH }
if ($env:HIGHLIGHT_STUDIO_SIGN_PFX_PASSWORD -and !$env:CSC_KEY_PASSWORD) { $env:CSC_KEY_PASSWORD = $env:HIGHLIGHT_STUDIO_SIGN_PFX_PASSWORD }

function Run-Step([string]$Name, [scriptblock]$Action) {
  Write-Host "`n=== $Name ===" -ForegroundColor Cyan
  $global:LASTEXITCODE = 0
  & $Action
  if (!$?) { throw "$Name failed." }
  if ($LASTEXITCODE -ne 0) { throw "$Name failed with code $LASTEXITCODE" }
}

if (!$SkipFfmpegDownload) {
  $Ffmpeg = Join-Path $Root "vendor\ffmpeg\bin\ffmpeg.exe"
  $Ffprobe = Join-Path $Root "vendor\ffmpeg\bin\ffprobe.exe"
  if (!(Test-Path $Ffmpeg) -or !(Test-Path $Ffprobe)) {
    if ($env:HIGHLIGHT_STUDIO_FFMPEG_SHA256) {
      $FfmpegArgs = @{ Sha256 = $env:HIGHLIGHT_STUDIO_FFMPEG_SHA256 }
      if ($env:HIGHLIGHT_STUDIO_FFMPEG_URL) { $FfmpegArgs.Url = $env:HIGHLIGHT_STUDIO_FFMPEG_URL }
      Run-Step "Prepare checksum-pinned bundled FFmpeg" { & (Join-Path $PSScriptRoot "fetch_ffmpeg.ps1") @FfmpegArgs }
    } elseif ($AllowUnverifiedFfmpegDownload) {
      Write-Warning "Downloading a mutable FFmpeg build without a pinned checksum. Use only for CI/testing."
      Run-Step "Prepare bundled FFmpeg" { & (Join-Path $PSScriptRoot "fetch_ffmpeg.ps1") }
    } else {
      throw "FFmpeg is missing. Run fetch_ffmpeg.ps1 with a verified -Sha256, or pass -AllowUnverifiedFfmpegDownload only for a test build."
    }
  }
}

if (!$InstallerOnly) {
  if (!(Test-Path $BuildVenv)) {
    Run-Step "Create production build virtual environment" { python -m venv $BuildVenv }
  }
  $Python = Join-Path $BuildVenv "Scripts\python.exe"
  Run-Step "Upgrade production build pip" { & $Python -m pip install --upgrade pip }
  Run-Step "Install production build dependencies" { & $Python -m pip install -r backend\requirements-build.txt }

  Run-Step "Install frontend dependencies" { npm --prefix frontend ci }
  if (!$SkipTests) {
    if (!(Test-Path $TestVenv)) {
      Run-Step "Create test virtual environment" { python -m venv $TestVenv }
    }
    $TestPython = Join-Path $TestVenv "Scripts\python.exe"
    Run-Step "Upgrade test environment pip" { & $TestPython -m pip install --upgrade pip }
    Run-Step "Install Python test dependencies" { & $TestPython -m pip install -r backend\requirements-dev.txt }
    Run-Step "Backend tests" { & $TestPython -m pytest -q }
    Run-Step "Python lint" { & $TestPython -m ruff check backend tests tools }
    Run-Step "Frontend tests" { npm --prefix frontend test }
    Run-Step "Frontend lint" { npm --prefix frontend run lint }
  }
  Run-Step "Build frontend" { npm --prefix frontend run build }

  $EngineDist = Join-Path $Root "build\desktop\engine"
  $EngineWork = Join-Path $Root "build\desktop\pyinstaller-work"
  Remove-Item $EngineDist -Recurse -Force -ErrorAction SilentlyContinue
  Remove-Item $EngineWork -Recurse -Force -ErrorAction SilentlyContinue
  Run-Step "Build standalone engine" {
    & $Python -m PyInstaller --noconfirm --clean --distpath $EngineDist --workpath $EngineWork tools\desktop\HighlightStudioEngine.spec
  }
  $EngineExe = Join-Path $EngineDist "HighlightStudioEngine\HighlightStudioEngine.exe"
  Run-Step "Verify packaged engine version and startup" { & $Python tools\desktop\verify_engine_runtime.py $EngineExe "v$Version" --app-root $Root }
  Run-Step "Sign standalone engine when certificate is configured" { & (Join-Path $PSScriptRoot "sign_engine.ps1") -EnginePath $EngineExe }
}

$ValidatorPython = if (Test-Path (Join-Path $BuildVenv "Scripts\python.exe")) { Join-Path $BuildVenv "Scripts\python.exe" } else { "python" }
$PrereqArgs = @("tools\desktop\check_hybrid_prereqs.py", "--require-engine", "--require-windows-bins")
if ($UpdateUrl) { $PrereqArgs += "--require-update-url" }
if ($RequireSigned) { $PrereqArgs += "--require-paid-beta-config" }
Run-Step "Validate hybrid resources" { & $ValidatorPython @PrereqArgs }
if ($MassRelease) {
  if (!$MassReleaseEvidencePath -or !(Test-Path $MassReleaseEvidencePath)) { throw "Mass release requires -MassReleaseEvidencePath." }
  if (!$BenchmarkReportPath -or !(Test-Path $BenchmarkReportPath)) { throw "Mass release requires -BenchmarkReportPath." }
  $GateData = Join-Path $Root "build\mass-release-gate"
  New-Item -ItemType Directory -Path $GateData -Force | Out-Null
  Copy-Item $MassReleaseEvidencePath (Join-Path $GateData "mass_release_evidence.json") -Force
  Copy-Item $BenchmarkReportPath (Join-Path $GateData "quality_benchmark_report.json") -Force
  $env:HIGHLIGHT_STUDIO_DATA_DIR = $GateData
  $env:HIGHLIGHT_STUDIO_UPDATE_URL = [string]$UpdateUrl
  Run-Step "Mass release gate" { & $ValidatorPython tools\release\check_mass_release.py --strict }
}
Run-Step "Install Electron dependencies" { npm --prefix desktop\electron ci }
if (!$SkipTests) {
  Run-Step "Electron security tests" { npm --prefix desktop\electron test }
  Run-Step "Electron dependency audit" { npm --prefix desktop\electron audit --audit-level=high }
}
Run-Step "Build NSIS installer and portable EXE" { npm --prefix desktop\electron run dist:win }
$ArtifactsDir = Join-Path $Root "build\desktop\installer"
Run-Step "Create auto-update manifest" { & $ValidatorPython tools\desktop\write_update_manifest.py $ArtifactsDir $Version }
Run-Step "Verify Windows artifacts" { & (Join-Path $PSScriptRoot "verify_windows_artifacts.ps1") -ArtifactsDir $ArtifactsDir -RequireSigned:$RequireSigned }

Write-Host "`nHybrid desktop artifacts:" -ForegroundColor Green
Get-ChildItem build\desktop\installer | Format-Table Name, Length, LastWriteTime
Write-Host "Runtime data will be stored in LOCALAPPDATA\HighlightStudio; projects in Videos\Highlight Studio."
